{{- if .Values.ingressExternal -}}
{{- if .Values.ingressExternal.enabled -}}
{{- $serviceName := include "fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-ext
  labels:
    app: {{ template "name" . }}
    chart: springboot-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ required "'project' value not found" .Values.project }}-app: "true"
  annotations:
    {{- range $key, $value := .Values.ingressExternal.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    kubernetes.io/ingress.class: {{ required "Required ingressExternal.ingressClass value not set" .Values.ingressExternal.ingressClass }}
    {{ if .Values.ingressExternal.kong -}}
    configuration.konghq.com: {{ template "fullname" . }}-ext
    {{- end}}
spec:
  rules:
  - host: {{ required "Required ingressExternal.hostname value not set" .Values.ingressExternal.hostname }}
    http:
      paths:
        {{- range $path := .Values.ingressExternal.paths }}
        - path: {{ if typeIs "string" $path }}{{ $path }}{{ else }}{{ $path.path }}{{ end }}
          pathType: {{ if typeIs "string" $path }}ImplementationSpecific{{ else }}{{ $path.pathType | default "ImplementationSpecific" }}{{ end }}
          backend:
              service:
                name: {{ $serviceName }}
                port: 
                  number: {{ $servicePort }}
        {{- end}}
  {{ if .Values.ingressExternal.tls -}}      
  tls:
  - hosts:
    - {{ required "Required ingressExternal.hostname value not set" .Values.ingressExternal.hostname }}
    {{ if .Values.ingressExternal.tls.tlsSecretName -}}
    secretName: {{ .Values.ingressExternal.tls.tlsSecretName }}
    {{- end}}
  {{- end}}
{{ if .Values.ingressExternal.kong -}}
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: {{ template "fullname" . }}-ext
  labels:
    app: {{ template "name" . }}
    chart: springboot-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ required "'project' value not found" .Values.project }}-app: "true"
proxy:
  path: /
route:
  protocols:
  - http
  strip_path: {{ .Values.ingressExternal.kong.stripPath }}
  preserve_host: {{ .Values.ingressExternal.kong.preserveHost }}
{{- end -}}
{{- end -}}
{{- end -}}
