{{- define "hasSensitive" }}
  {{- range $k, $v := . }}
    {{- if hasKey $v "sensitive" }}
true
    {{- end }}
  {{- end }}
{{- end }}
{{- if include "hasSensitive" .Values.env -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secret
  labels:
    app: {{ template "fullname" . }}
    chart: springboot-{{ .Chart.Version | replace "+" "_" }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- range $name, $definition := .Values.env }}
    {{- if $definition.sensitive }}
  {{ $definition.key | default $name | quote }}: {{ required (printf "Value for variable env.%s.value is undefined" $name) $definition.value | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end -}}
