apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: springboot-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ required "'project' value not found" .Values.project }}-app: "true"
  {{- if .Values.service.annotations }}
  annotations: {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: {{ .Values.service.name }}
    {{- if .Values.service.otherPorts }}
    {{- range .Values.service.otherPorts }}
    {{- if .port }}
{{ toYaml (list (omit . "containerPort")) | indent 4 }}
    {{- end }}
    {{- end }}
    {{- end }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
