{{ if .Values.curator.enabled }}
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {{ template "fullname" . }}-curator
  labels:
    app: {{ template "fullname" . }}-curator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  schedule: 1 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: {{ .Values.curator.image | quote }}
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: {{ template "fullname" . }}-curator-config
          restartPolicy: OnFailure
{{ end }}
