apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
spec:
  ports:
    - port: 9300
      targetPort: 9300
      name: transport
    - port: 9200
      targetPort: 9200
      name: http
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
