apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-configurer
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-configurer
      labels:
        app: configurer
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      volumes:
      - name: config
        configMap:
          name: "{{ template "fullname" . }}-configurer"
      containers:
      - name: kong-configurer
        image: docker.inventi.io/fps-apigw-configurer:latest
        env:
        - name: KONG_ADMIN_SVC
          value: "{{ .Release.Name }}-kongadmin:8001"
        - name: KONGFIG_CONFIG_PATH 
          value: /etc/kongfig/config.yml
        #command: [ "/bin/sh", "-c", "kong migrations up" ]
        volumeMounts:
          - name: config
            mountPath: /etc/kongfig
      restartPolicy: Never
