apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "fullname" . }}-configurer"
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  client_id: {{ .Values.oauth.clientId | quote }}
  # TODO: Move to secret
  client_secret: {{ .Values.oauth.secret | quote }}
  config.yml: |
    consumers:
      - username: fps-app
        credentials:
          - name: oauth2
            attributes:
              name: FPS
              client_id: {{ .Values.oauth.clientId | quote }}
              client_secret: {{ .Values.oauth.secret | quote }}
              redirect_uri: "http://not-used.example.com"
    apis:
      {{- range $idx, $options := .Values.apis }}
      - name: {{ $options.name | quote }}
        ensure: {{ $options.ensure | quote }}
        attributes:
{{ toYaml $options.attributes | indent 10 }}
        plugins:
{{ toYaml $options.plugins | indent 10 }}
      {{- end }}
    plugins:
      - name: cors
        attributes:
          enabled: true
          config:
            credentials: false
            preflight_continue: false
            max_age: 7000
      
