apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.project }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ default $key | quote }}: {{ required (printf "Value for secret %s is undefined" $key) $value | b64enc | quote }}
{{ end }}
