output:
  type: elasticsearch
  elasticsearch:
    host: logging-elasticsearch.default.svc.cluster.local
    port: 9200
    scheme: http
    sslVerify: false
    reloadConnections: true
  cloudwatch:
    accessKey: ""
    secretKey: ""
    region: ""
    logGroupName: "fluentd-kubernetes"
  logentries:
    token: ""
  loggly:
    token: ""

collector:
  image:
    repository: docker.inventi.io/fps-deps/coreos/fluentd-kubernetes
    tag: v0.12-debian-elasticsearch
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 250Mi

aggregator:
  enabled: false
  replicas: 2
  image:
    repository: docker.inventi.io/fps-deps/coreos/fluentd-kubernetes
    tag: v0.12-debian-elasticsearch
  resources:
    limits:
      cpu: 2
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 250Mi

#serviceAccountName: fluentd
serviceAccountName: default
